using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Wasmtime.Component.SourceGenerators.Diagnostics;
using Wasmtime.Component.SourceGenerators.Emit;
using Wasmtime.Component.SourceGenerators.Wit;

namespace Wasmtime.Component.SourceGenerators;

/// <summary>
/// IIncrementalGenerator that turns <c>[ComponentBindings("path/to/world.wit")]</c>-annotated
/// partial classes into source-generated component bindings.
/// </summary>
/// <remarks>
/// This is the skeleton: it identifies the target class, validates that it is partial, locates
/// the referenced WIT file in <c>AdditionalTexts</c>, and emits a placeholder partial class so
/// the generator pipeline produces visible output. Subsequent commits replace the placeholder
/// with real WIT-driven type and function emission.
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class WitBindingsGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Wasmtime.Components.ComponentBindingsAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var bindingsRequests = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => BindingsRequest.From(ctx))
            .Where(static r => r is not null)!;

        // Generators read the Rust-produced JSON IR (`*.wit.json`) rather than parsing WIT
        // themselves; the .wit file is still tracked so users get a single AdditionalFiles entry.
        var witFiles = context.AdditionalTextsProvider
            .Where(static t =>
                t.Path.EndsWith(".wit", StringComparison.OrdinalIgnoreCase)
                || t.Path.EndsWith(".wit.json", StringComparison.OrdinalIgnoreCase))
            .Collect();

        var combined = bindingsRequests.Combine(witFiles);

        context.RegisterSourceOutput(combined, static (spc, pair) =>
        {
            var request = pair.Left;
            var files = pair.Right;
            if (request is null)
            {
                return;
            }

            Emit(spc, request, files);
        });
    }

    private static void Emit(
        SourceProductionContext spc,
        BindingsRequest request,
        ImmutableArray<AdditionalText> files)
    {
        if (!request.IsPartial)
        {
            spc.ReportDiagnostic(Diagnostic.Create(
                Descriptors.TargetMustBePartial,
                request.AttributeLocation,
                request.ClassName));
            return;
        }

        if (string.IsNullOrEmpty(request.WitPath))
        {
            spc.ReportDiagnostic(Diagnostic.Create(
                Descriptors.WitPathMissing,
                request.AttributeLocation,
                request.ClassName));
            return;
        }

        var jsonName = Path.GetFileName(request.WitPath) + ".json";
        var jsonMatch = files.FirstOrDefault(t =>
            string.Equals(Path.GetFileName(t.Path), jsonName, StringComparison.OrdinalIgnoreCase)
            || t.Path.EndsWith(jsonName, StringComparison.OrdinalIgnoreCase));

        if (jsonMatch is null)
        {
            spc.ReportDiagnostic(Diagnostic.Create(
                Descriptors.WitFileNotRegistered,
                request.AttributeLocation,
                jsonName));
            return;
        }

        var json = jsonMatch.GetText(spc.CancellationToken)?.ToString() ?? string.Empty;
        WitModel model;
        try
        {
            model = WitJsonReader.Parse(json);
        }
        catch (Exception ex)
        {
            spc.ReportDiagnostic(Diagnostic.Create(
                Descriptors.WitFileNotRegistered,
                request.AttributeLocation,
                $"failed to parse: {ex.Message}"));
            return;
        }

        var world = string.IsNullOrEmpty(request.World)
            ? model.Worlds.FirstOrDefault()
            : model.Worlds.FirstOrDefault(w => w.Name == request.World);

        if (world is null)
        {
            spc.ReportDiagnostic(Diagnostic.Create(
                Descriptors.WitFileNotRegistered,
                request.AttributeLocation,
                $"world '{request.World ?? "<default>"}' not found"));
            return;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(request.Namespace))
        {
            sb.Append("namespace ").Append(request.Namespace).AppendLine(";");
            sb.AppendLine();
        }

        sb.Append("partial class ").AppendLine(request.ClassName);
        sb.AppendLine("{");
        sb.Append("    public const string WitPath = \"").Append(EscapeString(request.WitPath)).AppendLine("\";");
        sb.Append("    public const string WitWorld = \"").Append(EscapeString(world.Name)).AppendLine("\";");
        sb.Append("    public const int WitTypeCount = ").Append(model.Types.Count).AppendLine(";");
        sb.Append("    public const int WitImportCount = ").Append(world.Imports.Count).AppendLine(";");
        sb.Append("    public const int WitExportCount = ").Append(world.Exports.Count).AppendLine(";");

        sb.AppendLine();
        sb.AppendLine("    public static readonly string[] WitExportNames =");
        sb.AppendLine("    {");
        foreach (var export in world.Exports)
        {
            sb.Append("        \"").Append(EscapeString(export.Name)).AppendLine("\",");
        }
        sb.AppendLine("    };");

        sb.AppendLine();
        sb.AppendLine("    public static readonly string[] WitTypeNames =");
        sb.AppendLine("    {");
        foreach (var type in model.Types)
        {
            sb.Append("        \"").Append(EscapeString(type.Name ?? "<anonymous>")).AppendLine("\",");
        }
        sb.AppendLine("    };");

        sb.AppendLine();
        var ctx = new EmitContext(model.Types);
        TypeEmitter.EmitNamedTypes(sb, model, ctx, indent: 4);

        sb.AppendLine();
        FunctionEmitter.EmitMethods(sb, request.ClassName, world, model, ctx, "    ");

        sb.AppendLine("}");

        var hint = $"{request.ClassName}.WitBindings.g.cs";
        spc.AddSource(hint, SourceText.From(sb.ToString(), Encoding.UTF8));

        spc.ReportDiagnostic(Diagnostic.Create(
            Descriptors.GeneratedSummary,
            request.AttributeLocation,
            request.WitPath,
            world.Name));
    }

    private static string EscapeString(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private sealed record BindingsRequest(
        string ClassName,
        string Namespace,
        string WitPath,
        string? World,
        bool IsPartial,
        Location AttributeLocation)
    {
        public static BindingsRequest? From(GeneratorAttributeSyntaxContext ctx)
        {
            if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol)
            {
                return null;
            }

            var attribute = ctx.Attributes[0];
            var args = attribute.ConstructorArguments;
            string? witPath = null;
            string? world = null;
            if (args.Length >= 1 && args[0].Value is string p)
            {
                witPath = p;
            }
            if (args.Length >= 2 && args[1].Value is string w)
            {
                world = w;
            }

            var declaration = (ClassDeclarationSyntax)ctx.TargetNode;
            var isPartial = declaration.Modifiers.Any(m => m.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PartialKeyword));

            return new BindingsRequest(
                ClassName: typeSymbol.Name,
                Namespace: typeSymbol.ContainingNamespace.IsGlobalNamespace
                    ? string.Empty
                    : typeSymbol.ContainingNamespace.ToDisplayString(),
                WitPath: witPath ?? string.Empty,
                World: world,
                IsPartial: isPartial,
                AttributeLocation: attribute.ApplicationSyntaxReference?.GetSyntax().GetLocation() ?? Location.None);
        }
    }
}
