using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Wasmtime.Component.SourceGenerators.Diagnostics;

namespace Wasmtime.Component.SourceGenerators;

/// <summary>
/// IIncrementalGenerator that turns <c>[ComponentBindings("path/to/world.wit")]</c>-annotated
/// partial classes into source-generated component bindings.
/// </summary>
/// <remarks>
/// This is the skeleton: it identifies the target class, validates that it is partial, locates
/// the referenced WIT file in <c>AdditionalTexts</c>, and emits a placeholder partial class so
/// the generator pipeline produces visible output. Subsequent commits replace the placeholder
/// with real WIT-driven type and function emission.
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class WitBindingsGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Wasmtime.Components.ComponentBindingsAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var bindingsRequests = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => BindingsRequest.From(ctx))
            .Where(static r => r is not null)!;

        var witFiles = context.AdditionalTextsProvider
            .Where(static t => t.Path.EndsWith(".wit", System.StringComparison.OrdinalIgnoreCase))
            .Collect();

        var combined = bindingsRequests.Combine(witFiles);

        context.RegisterSourceOutput(combined, static (spc, pair) =>
        {
            var request = pair.Left;
            var files = pair.Right;
            if (request is null)
            {
                return;
            }

            Emit(spc, request, files);
        });
    }

    private static void Emit(
        SourceProductionContext spc,
        BindingsRequest request,
        ImmutableArray<AdditionalText> files)
    {
        if (!request.IsPartial)
        {
            spc.ReportDiagnostic(Diagnostic.Create(
                Descriptors.TargetMustBePartial,
                request.AttributeLocation,
                request.ClassName));
            return;
        }

        if (string.IsNullOrEmpty(request.WitPath))
        {
            spc.ReportDiagnostic(Diagnostic.Create(
                Descriptors.WitPathMissing,
                request.AttributeLocation,
                request.ClassName));
            return;
        }

        var match = files.FirstOrDefault(t =>
            string.Equals(Path.GetFileName(t.Path), Path.GetFileName(request.WitPath), System.StringComparison.OrdinalIgnoreCase)
            || t.Path.EndsWith(request.WitPath, System.StringComparison.OrdinalIgnoreCase));

        if (match is null)
        {
            spc.ReportDiagnostic(Diagnostic.Create(
                Descriptors.WitFileNotRegistered,
                request.AttributeLocation,
                request.WitPath));
            return;
        }

        var witText = match.GetText(spc.CancellationToken)?.ToString() ?? string.Empty;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(request.Namespace))
        {
            sb.Append("namespace ").Append(request.Namespace).AppendLine(";");
            sb.AppendLine();
        }

        sb.Append("partial class ").AppendLine(request.ClassName);
        sb.AppendLine("{");
        sb.Append("    /// <summary>WIT file path supplied via [ComponentBindings].</summary>").AppendLine();
        sb.Append("    public const string WitPath = \"").Append(EscapeString(request.WitPath)).AppendLine("\";");
        sb.Append("    /// <summary>Selected world from the WIT file (null if unspecified).</summary>").AppendLine();
        sb.Append("    public const string? WitWorld = ");
        if (request.World is null)
        {
            sb.AppendLine("null;");
        }
        else
        {
            sb.Append('\"').Append(EscapeString(request.World)).AppendLine("\";");
        }
        sb.Append("    /// <summary>Number of bytes in the source WIT file at generation time.</summary>").AppendLine();
        sb.Append("    public const int WitSourceLength = ").Append(witText.Length).AppendLine(";");
        sb.AppendLine("}");

        var hint = $"{request.ClassName}.WitBindings.g.cs";
        spc.AddSource(hint, SourceText.From(sb.ToString(), Encoding.UTF8));

        spc.ReportDiagnostic(Diagnostic.Create(
            Descriptors.GeneratedSummary,
            request.AttributeLocation,
            request.WitPath,
            request.World ?? "<default>"));
    }

    private static string EscapeString(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private sealed record BindingsRequest(
        string ClassName,
        string Namespace,
        string WitPath,
        string? World,
        bool IsPartial,
        Location AttributeLocation)
    {
        public static BindingsRequest? From(GeneratorAttributeSyntaxContext ctx)
        {
            if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol)
            {
                return null;
            }

            var attribute = ctx.Attributes[0];
            var args = attribute.ConstructorArguments;
            string? witPath = null;
            string? world = null;
            if (args.Length >= 1 && args[0].Value is string p)
            {
                witPath = p;
            }
            if (args.Length >= 2 && args[1].Value is string w)
            {
                world = w;
            }

            var declaration = (ClassDeclarationSyntax)ctx.TargetNode;
            var isPartial = declaration.Modifiers.Any(m => m.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PartialKeyword));

            return new BindingsRequest(
                ClassName: typeSymbol.Name,
                Namespace: typeSymbol.ContainingNamespace.IsGlobalNamespace
                    ? string.Empty
                    : typeSymbol.ContainingNamespace.ToDisplayString(),
                WitPath: witPath ?? string.Empty,
                World: world,
                IsPartial: isPartial,
                AttributeLocation: attribute.ApplicationSyntaxReference?.GetSyntax().GetLocation() ?? Location.None);
        }
    }
}
